pipeline {
  agent any
  stages {
    stage('Stage-01') {
      steps {
        echo 'build-01'
        bat 'scm.1/dir01.bat'
        bat 'scm.1/dir02.bat'
      }
    }
    stage('Stage-02') {
      steps {
        echo 'build-02'
      }
    }
    stage('End') {
      steps {
        echo 'end'
      }
    }
  }
}
